name: Events Demo 1
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    types: [opened, edited]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Output event data
      # run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ./fourth-demo
      - name: Test code
        run: npm run test
        working-directory: ./fourth-demo
      - name: Build code
        run: npm run build
        working-directory: ./fourth-demo
      - name: Deploy project
        run: echo "Deploying..."
