name: Third Demo Workflow Challenge
on: [push, workflow_dispatch]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: ./third-demo
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./third-demo
      - name: Lint code
        run: npm run lint
        working-directory: ./third-demo
  deploy:
    needs: build-test-lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
        working-directory: ./third-demo
      - name: Build project
        run: npm run build
        working-directory: ./third-demo
      - name: Deploy
        run: echo "Deploying project..."
